Pandas: Panel Data
- Pandas temelinde ekonometrik ve finansal çalışmalar, panel veri çalışmaları, zaman serisi çalışmaları için doğmuştur.
- Panel Data ne demek: kesit veri ve zaman serisi verisinin bir arada olduğu veritipidir. Bu doğrultuda, klasik veri tutma yaklaşımları yerine, zaman indeksini daha fazla önemseyen veri tutma yaklaşımı söz konusudur.

Pandas kütüphanesi, Numpy'ın alternatifi değildir! Numpy'ın özelliklerini kullanan ve genişleten bir kütüphanedir.

Numpy'dan farklı olarak, bizlere yapısal verisetleriyle daha esnek bir şekilde çalışma imkanı sağlar. Örneğin Numpy, fixed type idi ancak Pandas kategorik ve numerik verilerle bir arada çalışmaya imkan sağlar.

**Veri manipülasyonu, veri analizi ve veri görselleştirme** için yazılmış açık kaynak kodlu bir kütüphanedir

# Pandas Array'i Oluşturmak

Numpy'dan farklı olarak array içerisindeki elemanların indeks bilgileri ve veritipleri de tutulur Pandas'da

In [4]:
import pandas as pd

In [5]:
pd.Series([100,200,300,400,500,600,700,800])

# görüldüğü üzere bir liste oluşturduğumuzda liste içerisinde
# o listenin elemanları, listenin veritipi ve elemanların kendileri tutulur

0    100
1    200
2    300
3    400
4    500
5    600
6    700
7    800
dtype: int64

In [6]:
liste = pd.Series([100,200,300,400,500,600,700,800])

In [7]:
liste.axes # burada bize indexler hakkında bilgi veriyor. 0'dan başladı, 5'de bitti, 1'er 1'er arttı diyor

[RangeIndex(start=0, stop=8, step=1)]

In [8]:
liste.dtype

dtype('int64')

In [9]:
liste.size

8

In [10]:
liste.ndim

1

In [11]:
liste.values

array([100, 200, 300, 400, 500, 600, 700, 800], dtype=int64)

In [12]:
liste.head() # listenin içerisinden örnek 5 tane değer getirir, hani gör neye benziyor diye.

0    100
1    200
2    300
3    400
4    500
dtype: int64

In [13]:
pd.Series([100,200,300,400,500], index=[1,3,5,7,9]) # bu şekilde index numaralarını değiştirebiliriz.

1    100
3    200
5    300
7    400
9    500
dtype: int64

In [14]:
pd.Series([100,200,300,400,500], index=[1,2.64543,"üç","dört",5]) # bu şekilde farklı datatype indexleri verebilirz

1          100
2.64543    200
üç         300
dört       400
5          500
dtype: int64

In [15]:
wierdList = pd.Series([100,200,300,400,500], index=[1,2.64543,"üç","dört",5])

wierdList["üç"] # bu şekilde index değerini vererek her zamanki gibi ulaşabiliri

300

In [16]:
list(wierdList.items()) # dictonarylerde olduğu gibi burada da indexler ve onların değerlerini alabiliriz

[(1, 100), (2.64543, 200), ('üç', 300), ('dört', 400), (5, 500)]

In [17]:
list(wierdList.values)

[100, 200, 300, 400, 500]

In [18]:
list(wierdList.keys())

[1, 2.64543, 'üç', 'dört', 5]

In [19]:
# Pandas'da Dictionary:

myPandasDict = pd.Series({"on":10, "ikiyüzelli":250, "anahtar":"key"})
myPandasDict

on             10
ikiyüzelli    250
anahtar       key
dtype: object

In [20]:
# Listeleri birleştirme

list1 = pd.Series([1,2,3,4,5])
list2 = pd.Series([6,7,8,9,10])

pd.concat([list1,list2]) # birleştirme işlemini concat yapıyor

0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

In [21]:
1 in list1 # bir elemanın o liste içerisinde olup olmadığına bu şekilde bakabiliriz

True

In [22]:
list2[[0,1]] # fancy ile birden fazla elemanı tekte sorgulama

0    6
1    7
dtype: int64

# Pandas DataFrame Oluşturma

Neden Numpy varken Pandas DataFrame'ine ihtiyacımız var? Numpy'in fixed type olması bazen işleri zorlaştırıyor ve bu sebeple Pandas kullanıyoruz.

Numpy daha teorik, matematik, işlemsel olarak yardımcı olurken Pandas iyi ve esnek bir araç. Pandas makina öğrenmesi modellerine vereceğimiz verisetleri olarak düşünülebilir. Biri pratikte iyi, diğeri teorikte. Örneğin biz Pandas'da bir matematiksel işlem yaptığımızda bile arkaplanda zaten Numpy kullanılıyor.

In [25]:
liste = [10,20,30,40,50]

In [26]:
pd.DataFrame(liste, columns = ["My List"])

   My List
0       10
1       20
2       30
3       40
4       50

In [27]:
# bunu istersek birden fazla değişkenli de yapabilirdik: 

import numpy as np

m = np.arange(1,10).reshape((3,3))

m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
pd.DataFrame(m, columns = ["Column1","Column2","Column3"], index=["Row1","Row2","Row3"])

      Column1  Column2  Column3
Row1        1        2        3
Row2        4        5        6
Row3        7        8        9

# Eleman İşlemleri

In [30]:
import numpy as np
s1 = np.random.randint(10, size = 5)
s2 = np.random.randint(10, size = 5)
s3 = np.random.randint(10, size = 5)          # numpy arrayleri

In [31]:
sozluk = {"var1": s1, "var2": s2, "var3": s3} # default sözlük veritipi

sozluk

{'var1': array([2, 8, 5, 5, 8]),
 'var2': array([2, 5, 7, 6, 2]),
 'var3': array([0, 9, 3, 1, 1])}

In [32]:
df = pd.DataFrame(sozluk)                       # pandas DataFrame'i.

# son 3 hücrede artık iç içe farklı veriyapılarını kullanmaya başladık

df

   var1  var2  var3
0     2     2     0
1     8     5     9
2     5     7     3
3     5     6     1
4     8     2     1

In [33]:
df[0:1]

   var1  var2  var3
0     2     2     0

In [34]:
df.index=["a","b","c","d","e"]

In [35]:
df

   var1  var2  var3
a     2     2     0
b     8     5     9
c     5     7     3
d     5     6     1
e     8     2     1

In [36]:
# Silme İşlemi

df.drop("a", axis=0) # a isimli satırı sil demiş olduk ancak bu kalıcı bir silme işlemi değil.

# eğer inplace keywordünü kullanırsak silme işlemi kalıcı hale gelir df.drop("a", axis=0, inplace=True) şeklinde

   var1  var2  var3
b     8     5     9
c     5     7     3
d     5     6     1
e     8     2     1

In [37]:
df["var4"] = df["var3"] * df["var2"] 

# eğer var olmayan bir sütun veya satırı, [] içerisine yazarsak, bu yeni bir oluşturma işlemi olarak algılanır
# bu şekilde yeni sütunumuzu önceki sütunların çarpımı olarak yaratabiliriz

In [38]:
df

   var1  var2  var3  var4
a     2     2     0     0
b     8     5     9    45
c     5     7     3    21
d     5     6     1     6
e     8     2     1     2

In [39]:
df.drop("var4", axis=1, inplace=True) # kalıcı olarak var4 sütununu sildik

In [40]:
df

   var1  var2  var3
a     2     2     0
b     8     5     9
c     5     7     3
d     5     6     1
e     8     2     1

In [41]:
silinecekler = ["var1","var2"]
df.drop(silinecekler,axis=1) # fency kullanarak da bu işlemi yapabiliriz

   var3
a     0
b     9
c     3
d     1
e     1

# Gözlem ve Değişken Seçimi

Pandas kullanımında en çok hata alınan konuları ele alacağız. **Loc ve ILoc**

In [44]:
import numpy as np
import pandas as pd

m = np.random.randint(1,30,size=(10,3)) # numpy ile verisetimizi oluşturduk
df = pd.DataFrame(m, columns = ["var1","var2","var3"]) # pandas ile verisetimizi görüntüledik

df

   var1  var2  var3
0    19    19    13
1     6    27     6
2    25    13    22
3    25    26    26
4    12    24     8
5    23    22    18
6    29     5    20
7    11    27    10
8     3    16    22
9    11     5    18

**loc** : Tanımlandığı şekli ile seçim yapmak için kullanılır

* loc → Label Location (Etiket tabanlı)
* Sayısal indeks pozisyonları kullanır (0, 1, 2, 3...)
* Her zaman çalışır
* Boolean değer kabul eder

In [47]:
df.loc[0:3] # 0'dan 3'e kadar, yani 3 dahil olmamak üzere almasını bekleriz ama loc'da alınır, ilocta alınmaz

   var1  var2  var3
0    19    19    13
1     6    27     6
2    25    13    22
3    25    26    26

**iloc** : Alışık olduğumuz indexleme mantığıyla seçim yapmak için kullanılır

* iloc → Integer Location (Pozisyon tabanlı)
* Gerçek indeks etiketlerini kullanır
* İndeks etiketleri ne ise onları arar
* Boolean değer kabul etmez, yalnızca int (df.iloc[df.var1>15, :2] bu hata verir çünkü df.var1>15 ifadesi true false)

In [49]:
df.iloc[0:3] # bu normal, 0'dan 3'e kadar(3 dahil değil) şeklinde alıyor. ilactır ilac

   var1  var2  var3
0    19    19    13
1     6    27     6
2    25    13    22

In [50]:
df.iloc[:3,:2] # 3.satırdaki değere ve 2.sütundaki değere kadar al(son değerler dahil değil)

   var1  var2
0    19    19
1     6    27
2    25    13

In [51]:
df.loc[:3,:"var2"]

# buradaki column kısmına iloctaki gibi :2 yazamadık çünkü yazsaydık hata alırdık. 
# Sebebi: loc: labeled Location tabanlı. eğer sütun kısmına :2 yazsaydık gidip sütun isimlerinde "2" arayacaktı
# iloc ise 2.indexte bulunan şeyi gider alır, bu index olarak değil, 2 isminde bişe var mı diye bakar

   var1  var2
0    19    19
1     6    27
2    25    13
3    25    26

# Koşullu Eleman İşlemleri

In [53]:
import numpy as np
import pandas as pd

dataset = np.random.randint(1, 30, size=(10,3))
df = pd.DataFrame(dataset, columns=["var1","var2","var3"])

df

   var1  var2  var3
0    29    22    29
1    15    21    16
2    11    15    11
3    19    13    27
4    12    22    20
5    10     5    10
6    14    27    26
7    17    24    20
8    20    11    19
9    22    18    11

In [54]:
df[df.var1>15] # var1 içerisinde 15'den büyük değerleri diğer var2 ve var3 sütunlarıyla birlikte getir

   var1  var2  var3
0    29    22    29
3    19    13    27
7    17    24    20
8    20    11    19
9    22    18    11

In [55]:
df[df.var1>15]["var1"] # var1 içerisinde 15'den büyük değerleri getir ama diğer var2 ve var3 sütunlarını getirme

0    29
3    19
7    17
8    20
9    22
Name: var1, dtype: int32

In [56]:
# Slicing'i DataFrame'de direkt yapamayız, bunun için loc ve iloc kullanmalıyız

df.loc[df.var1>15, ["var2","var3"]] # var1'de 15'den büyük olan değerlerin var2 ve var3 sütunlarındaki değerlerini getir
df[df.var1>15][["var2","var3"]]     # bu ve bir önceki satır tıpatıp aynı şey. birinde slicing yaptık birinde fancy

   var2  var3
0    22    29
3    13    27
7    24    20
8    11    19
9    18    11

# DataFrame Birleştirme (Join) İşlemleri

Elimizde çoğu zaman 1 den fazla DataFrame olacak. Bu dataframelerin taşıdıkları bilgiler bir araya getirilmek istendiğinde DataFrame joint etme işlemleri yapılır.

In [59]:
import numpy as np
import pandas as pd

dataset1 = np.random.randint(1, 30, size = (5,3))
df1 = pd.DataFrame(dataset1, columns=["var1","var2","var3"])
 
df1

   var1  var2  var3
0    16    13     8
1    10    17     6
2    18    27    20
3    18    29    12
4    16    11     2

In [60]:
dataset2 = np.random.randint(1,30,size=(5,3))
df2 = pd.DataFrame(dataset2, columns=["var1","var2","var3"])
df2

   var1  var2  var3
0    13    15    17
1    20    24    21
2     7    26    20
3    29    28    21
4    13    21    14

In [61]:
# Yol 1: Concat

pd.concat([df1,df2])

# iki adet dataframe'i birleştirmenin yollarından biri de concat kullanmaktır
# şu an iki adet dataframe'i birleştirdik
# buradaki tek problem indexler kendini tekrar ediyor. 0 1 2 3 4 sonra yine 0 1 2 3 4

   var1  var2  var3
0    16    13     8
1    10    17     6
2    18    27    20
3    18    29    12
4    16    11     2
0    13    15    17
1    20    24    21
2     7    26    20
3    29    28    21
4    13    21    14

In [62]:
# tekrar eden index problemini gidermek için:

pd.concat([df1,df2],ignore_index=True) # ignore_index=True yaparsak indexleri birbirinin devamı yapar

   var1  var2  var3
0    16    13     8
1    10    17     6
2    18    27    20
3    18    29    12
4    16    11     2
5    13    15    17
6    20    24    21
7     7    26    20
8    29    28    21
9    13    21    14

Şu konulara **dikkat!!!!!!** edilmeli: Eğer her iki DataFrame'de de aynı sayıda ve aynı column isimleri yoksa bu sorun çıkartacaktır. Örneğin bir DataFrame'de var1 var2 varken diğerinde yalnızca var3 varsa bu sorundur. Ya da isim farklılıkları varsa da sorun olacaktır. Her ikisinde de 3 adet column olabilir ancak bunların isimleri de birebir aynı olmalı ki sorun çıkmasın. Bu sorundan kaçınmak, sadece kesişimleri olan kısımları eklemek için şu kodu kullanırız: 

**pd.concat([df1,df2], join="inner")**

**pd.concat([df1, df2.reindex(columns=df1.columns)]) dersek de df2'ye göre yapmış oluruz**

In [64]:
# Şimdi bu bahsetmiş olduğum sorunu yaşamak için df2'nin column isimlerini değiştirelim ve neler olacak görelim!

df2.columns = ["var1","var2","deg1"] # var1 var2 var3 olmalıydı ama sonuncuyu değiştirdik

In [65]:
df1

   var1  var2  var3
0    16    13     8
1    10    17     6
2    18    27    20
3    18    29    12
4    16    11     2

In [66]:
df2 # Görüleceği üzere elimizde 2 tane farklı table isimli DataFrameler var.

   var1  var2  deg1
0    13    15    17
1    20    24    21
2     7    26    20
3    29    28    21
4    13    21    14

In [67]:
pd.concat([df1,df2], ignore_index=True) # deg1 değeri, df1 için tamamen anlamsız

   var1  var2  var3  deg1
0    16    13   8.0   NaN
1    10    17   6.0   NaN
2    18    27  20.0   NaN
3    18    29  12.0   NaN
4    16    11   2.0   NaN
5    13    15   NaN  17.0
6    20    24   NaN  21.0
7     7    26   NaN  20.0
8    29    28   NaN  21.0
9    13    21   NaN  14.0

In [68]:
pd.concat([df1,df2],join="inner", ignore_index=True) 


# Her iki DataFrame'in kesişimlerine göre birleştirildi. Ortak sütunlar alınır yani. 
# Her ikisinde de olan var1 ve var2 tablosu var, o sebeple df1'de ki table 3 diğerinde, 
# df2'de ki dg1 de diğerinde olmadığından bu ikisi kaldırıldı

   var1  var2
0    16    13
1    10    17
2    18    27
3    18    29
4    16    11
5    13    15
6    20    24
7     7    26
8    29    28
9    13    21

In [69]:
pd.concat([df1, df2.reindex(columns=df1.columns)], ignore_index=True)

# burada da df1'de ki tüm tabloları getir, df2'de olupta 1 de olmayanı getirme demiş olduk.
# yani df1'e göre concat et

   var1  var2  var3
0    16    13   8.0
1    10    17   6.0
2    18    27  20.0
3    18    29  12.0
4    16    11   2.0
5    13    15   NaN
6    20    24   NaN
7     7    26   NaN
8    29    28   NaN
9    13    21   NaN

# İleri Birleştirme İşlemleri

Birebir birleştirme: **Merge**

In [72]:
import pandas as pd

df1 = pd.DataFrame({"Calisanlar":["Ali", "Veli", "Ayşe", "Fatma"], "Grup":["Muhasebe","Muhendislik","Muhendislik","İK"]})
df1

  Calisanlar         Grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayşe  Muhendislik
3      Fatma           İK

In [73]:
df2 = pd.DataFrame({"Calisanlar":["Ayşe","Ali","Veli","Fatma"], "İlk Giris":[2010,2009,2014,2019]})
df2

  Calisanlar  İlk Giris
0       Ayşe       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [74]:
pd.concat([df1,df2], ignore_index=True) # Normali bu. isimler tekrar ediyor, NaNlar var vs. Düzeltilmiş hali aşağıda:

  Calisanlar         Grup  İlk Giris
0        Ali     Muhasebe        NaN
1       Veli  Muhendislik        NaN
2       Ayşe  Muhendislik        NaN
3      Fatma           İK        NaN
4       Ayşe          NaN     2010.0
5        Ali          NaN     2009.0
6       Veli          NaN     2014.0
7      Fatma          NaN     2019.0

In [75]:
pd.merge(df1,df2)

# Merge fonksiyonu, iki verisetinde de aynı olan değerlerin üzerine gelecek yeni bilgi varsa ekler
# Merge fonksiyonu hangi sütuna göre birleştireceğine kendi karar verir. 
# Burada her iki dataframe'de de çalışanlar sütunu olduğundan dolayı ona göre birleştirdi ancak biz de bunu ayarlayabiliriz.
# Ancak eğer her iki tabloda da ortak olarak bulunan başka bir değer varsa onu da yapabilirdik pd.merge(df1, df2, on="İlk Giris") gibi. Ortak değilse olmaz

  Calisanlar         Grup  İlk Giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayşe  Muhendislik       2010
3      Fatma           İK       2019

**Many to one**

In [77]:
# Yeni df3 isimli DataFrame'imiz.
df3 = pd.merge(df1,df2)
df3

  Calisanlar         Grup  İlk Giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayşe  Muhendislik       2010
3      Fatma           İK       2019

In [78]:
# Yeni df4 isimli DataFrame'imiz.

df4 = pd.DataFrame({"Grup":["Muhasebe","Muhendislik","İK"] ,"Mudur":["Caner", "Mustafa", "Berkcan"]})
df4

          Grup    Mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [79]:
pd.merge(df3,df4) # ortak sütn olan grupta df3'te 4 tane grup üyesi varken burada 3 tane var.

  Calisanlar         Grup  İlk Giris    Mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayşe  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

**Many to Many**

bu kısımdan bir bok anlamadığımdan pas geçtim

# Toplulaştırma ve Gruplama (Aggregation & Grouping)

Pandas DataFrame'inin **en önemli** bölümlerinden birisi! İleride, elimize bir veri seti geçtiğinde ve iş başa düştü, hadi bunu analiz edelim dediğimizde, veri setiyle uğraşmaya başladığımızda yapısal bazı sorunları giderdikten sonra ilk kullanacağımız fonksiyonlar dizisi böyledir:

## Toplulaştırma(Aggregation)

Basit **Toplulaştırma** Fonksiyonları:

* count()
* first()
* last()
* mean()
* median()
* min()
* max()
* std()
* var()
* sum()

In [85]:
import seaborn as sns # bize verisetleri sağlayan kütüphanedir. Pratik bir şekilde içerisinden verisetlerini alıp üzerlerinde oynama yapacağız

In [86]:
df = sns.load_dataset("planets")
df

               method  number  orbital_period   mass  distance  year
0     Radial Velocity       1      269.300000   7.10     77.40  2006
1     Radial Velocity       1      874.774000   2.21     56.95  2008
2     Radial Velocity       1      763.000000   2.60     19.84  2011
3     Radial Velocity       1      326.030000  19.40    110.62  2007
4     Radial Velocity       1      516.220000  10.50    119.47  2009
...               ...     ...             ...    ...       ...   ...
1030          Transit       1        3.941507    NaN    172.00  2006
1031          Transit       1        2.615864    NaN    148.00  2007
1032          Transit       1        3.191524    NaN    174.00  2007
1033          Transit       1        4.125083    NaN    293.00  2008
1034          Transit       1        4.187757    NaN    260.00  2008

[1035 rows x 6 columns]

In [87]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [88]:
df.shape # 1035 adet gözlem birimi(satır), 6 adet değişken(sütun) var bu planets datasetinde

(1035, 6)

In [89]:
df["orbital_period"].mean()

2002.9175960947582

In [90]:
df["mass"].mean()

2.6381605847953216

In [91]:
df["mass"].min()

0.0036

In [92]:
df["mass"].sum()

1353.37638

In [93]:
df["mass"].std()

3.8186166509616046

In [94]:
df["mass"].var()

14.58183312700122

In [95]:
df.describe().T # veriseti içerisindeki tüm değerler için fonksiyonların uygulanmış hali

,count,mean,std,min,25%,50%,75%,max
number,1035.0,1.785507,1.240976,1.000000,1.00000,1.0000,2.000,7.0
orbital_period,992.0,2002.917596,26014.728304,0.090706,5.44254,39.9795,526.005,730000.0
mass,513.0,2.638161,3.818617,0.003600,0.22900,1.2600,3.040,25.0
distance,808.0,264.069282,733.116493,1.350000,32.56000,55.2500,178.500,8500.0
year,1035.0,2009.070531,3.972567,1989.000000,2007.00000,2010.0000,2012.000,2014.0

In [96]:
# eğer datasetimiz içerisinde eksik veriler varsa(ki bu çok sık karşımıza çıkacak) bunları çıkartarak görme kodu:

df.dropna().describe().T

,count,mean,std,min,25%,50%,75%,max
number,498.0,1.734940,1.175720,1.0000,1.00000,1.000,2.0000,6.0
orbital_period,498.0,835.778671,1469.128259,1.3283,38.27225,357.000,999.6000,17337.5
mass,498.0,2.509320,3.636274,0.0036,0.21250,1.245,2.8675,25.0
distance,498.0,52.068213,46.596041,1.3500,24.49750,39.940,59.3325,354.0
year,498.0,2007.377510,4.167284,1989.0000,2005.00000,2009.000,2011.0000,2014.0

## Gruplama(Grouping)

Gruplama: Kategorik değişkenlerde olur.

Gruplama yapmak için değerlerin kategorik değişken olması gerekli ki tekrar ettiğinde gruplamak için anlamlı bir sebebimiz olsun
A,B,A,A,B,C,C,C gibi değerleri gruplarsın. Örneğin 3 tane C'nin x ortalaması şudur

In [99]:
df = pd.DataFrame({"gruplar": ["A","B","C","A","B","C"], "veri":[10,11,52,23,43,55]}, columns=["gruplar","veri"])
df

  gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [100]:
# eğer ben bir veri seti içerisinde tekrar eden değişkenlerin ortalama değerini vs merak edersem merge yapamam çünkü aynı veriseti içerisindeler.
# bu bir gruplama örneğidir.

df.groupby("gruplar") # şu anda biz dedik ki "dataframe'mime git ve gruplar değişkenine gir, oradaki kategorik sınıflar olan A,B ve C'yi tut

In [101]:
df.groupby("gruplar").mean() # 2 defa tekrar eden A,B ve C sınıflarını aldı ve kendi içlerinde grupladı, ardından ortalamalarını aldı

         veri
gruplar
A        16.5
B        27.0
C        53.5

In [102]:
df.groupby("gruplar").sum()

         veri
gruplar
A          33
B          54
C         107

In [103]:
df = sns.load_dataset("planets")
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [104]:
df.groupby("method")["orbital_period"].mean()

# df dataframe'ine git, oradaki uniq olan sınıfları kendi içlerinde grupla, bu grupladığın sınıfların orbital_period ortalamalarını ver

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [105]:
df.groupby("method")["mass"].sum()

method
Astrometry                          0.00000
Eclipse Timing Variations          10.25000
Imaging                             0.00000
Microlensing                        0.00000
Orbital Brightness Modulation       0.00000
Pulsar Timing                       0.00000
Pulsation Timing Variations         0.00000
Radial Velocity                  1341.65638
Transit                             1.47000
Transit Timing Variations           0.00000
Name: mass, dtype: float64

In [106]:
df.groupby("method")["distance"].describe() # farklı farklı method grupları için distancenin tüm işlemlerini getirdi

,count,mean,std,min,25%,50%,75%,max
method,,,,,,,,
Astrometry,2.0,17.875000,4.094148,14.98,16.4275,17.875,19.3225,20.77
Eclipse Timing Variations,4.0,315.360000,213.203907,130.72,130.7200,315.360,500.0000,500.00
Imaging,32.0,67.715937,53.736817,7.69,22.1450,40.395,132.6975,165.00
Microlensing,10.0,4144.000000,2076.611556,1760.00,2627.5000,3840.000,4747.5000,7720.00
Orbital Brightness Modulation,2.0,1180.000000,0.000000,1180.00,1180.0000,1180.000,1180.0000,1180.00
Pulsar Timing,1.0,1200.000000,NaN,1200.00,1200.0000,1200.000,1200.0000,1200.00
Pulsation Timing Variations,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Radial Velocity,530.0,51.600208,45.559381,1.35,24.4125,40.445,59.2175,354.00
Transit,224.0,599.298080,913.876990,38.00,200.0000,341.000,650.0000,8500.00
Transit Timing Variations,3.0,1104.333333,915.819487,339.00,597.0000,855.000,1487.0000,2119.00

# İleri Seviye Toplulaştırma İşlemleri (Aggregate, Filter, Transform, Apply)

In [108]:
import pandas as pd

df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                   "degisken1":[10,23,33,22,11,99],
                   "degisken2":[100,253,333,262,111,969]})
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

## Aggregate()

In [110]:
df.groupby("gruplar").mean() # Burada önemli olan şey aggrigator(mean, median, std, etc) bir fonksiyon yazınca gruplama görünür hale geliyor

         degisken1  degisken2
gruplar
A             16.0      181.0
B             17.0      182.0
C             66.0      651.0

In [246]:
df.groupby("gruplar").aggregate(["min", "max", "median"]) 

# aggregate fonksiyonu ile tek satırda birden fazla toplulaştırma işlemi yapabiliriz
# biz burada python'ın kendisine default tanımlı min,max ve median fonksiyonlarını kullandık

        degisken1            degisken2
              min max median       min  max median
gruplar
A              10  22   16.0       100  262  181.0
B              11  23   17.0       111  253  182.0
C              33  99   66.0       333  969  651.0

In [254]:
df.groupby("gruplar").aggregate({"degisken1":"min", 
                                 "degisken2":"max"})

# her bir değişken(sütun) için farklı farklı istatistikler girebiliriz. Öncekilerde hep farklı değişkenler için aynı hesaplamaların sonucu
# gösterilirdi ancak şimdi aşağıda gördüğümüz tabloda değişken1 sütununda minimum değerler hesaplanırken değişken2 sütununda max değerler hesaplanıyor

         degisken1  degisken2
gruplar
A               10        262
B               11        253
C               33        969

## Filter()

Önceden basit anlamda filter yaptık. Şu anda da benzer şekilde dataframe içerisindeki değerler içerisinden filtrelediğimiz değerleri almaya çalışıcaz ancak kendi yazacağımız fonksiyona göre. Önceden pd.df(df.value1>15) gibi bir şey yapmıştık, şimdi bu parantez içerisine kendi yazdığımız fonksiyonu vereceğiz

In [258]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                   "degisken1":[10,23,33,22,11,99],
                   "degisken2":[100,253,333,262,111,969]})
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [263]:
def filter_function(x): # A,B ve C değerlerinden degisken1 sütununda standart sapması 9'dan büyük olan değerleri getir
    return x["degisken1"].std() > 9

In [271]:
df.groupby("gruplar").filter(filter_function)

# görüldüğü üzere standart sapması 9'dan küçük olan A ve B sınıflarını eledik, bu koşulu sağlayan C klasını aldık kendi yazdığımız fonksiyonla

  gruplar  degisken1  degisken2
2       C         33        333
5       C         99        969

## Transform()

In [274]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                   "degisken1":[10,23,33,22,11,99],
                   "degisken2":[100,253,333,262,111,969]})
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [280]:
df["degisken1"]*10 # normalde, eskiden dönüşümleri bu şekilde gerçekleştirirdik

0    100
1    230
2    330
3    220
4    110
5    990
Name: degisken1, dtype: int64

In [300]:
df_degiskenler = df.iloc[:,1:3]
df_degiskenler.transform(lambda x:x*10)  # özetle transform fonksiyonu, istediğimiz bir fonksiyonu dataframe'imiz içerisinde çalıştırmamızı sağlar

# bir önceki hücrede yapılan şeyi yapmış olduk

   degisken1  degisken2
0        100       1000
1        230       2530
2        330       3330
3        220       2620
4        110       1110
5        990       9690

## Apply()

In [321]:
df = pd.DataFrame({"gruplar":["A","B","C","A","B","C"],
                   "degisken1":[10,23,33,22,11,99],
                   "degisken2":[100,253,333,262,111,969]})
df

  gruplar  degisken1  degisken2
0       A         10        100
1       B         23        253
2       C         33        333
3       A         22        262
4       B         11        111
5       C         99        969

In [323]:
df.apply(np.sum) # degisken1 ve degisken2 sütunlarının toplamlarını aldı

gruplar      ABCABC
degisken1       198
degisken2      2028
dtype: object

In [328]:
df_degiskenler = df.iloc[:,1:3]
df_degiskenler.apply(lambda x:x**2) # kendi yazdığımız fonksiyonları da kullanabiliriz

   degisken1  degisken2
0        100      10000
1        529      64009
2       1089     110889
3        484      68644
4        121      12321
5       9801     938961

In [332]:
def myOperation(x):
    return (x)*(x+17)/(5*2)

df_degiskenler.apply(myOperation)  # lambda olmayan kendi yazdığımız fonksiyonları da kullanabiliriz

   degisken1  degisken2
0       27.0     1170.0
1       92.0     6831.0
2      165.0    11655.0
3       85.8     7309.8
4       30.8     1420.8
5     1148.4    95543.4

In [344]:
df.groupby("gruplar").apply("sum")

         degisken1  degisken2
gruplar
A               32        362
B               34        364
C              132       1302

# Pivot Tablolar

Verisetleri üzerinde bazı satır ve sütun işlemleri yaparak, verisetini amaca uygun getirmek için kullanılan yapılardır. Groupby işlemiyle karıştırılabilir, groupby'ın çok boyutlu halidir gibi düşünülebilir

In [348]:
import pandas as pd
import seaborn as sns

titanic = sns.load_dataset("titanic")

titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [363]:
titanic.groupby("sex")["age"].mean()  

# kadınların yaş ortalamasıyla erkeklerin yaş ortalamasını aldık
# burada aslında ilkel bir pivot işlemi yapmış olduk. Titankteki insanların cinsiyetlerin yaş ortalamsına bakmış olduk

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [369]:
titanic.groupby("sex")[["age"]].mean()

# burada sütun ekleyecek bu dediği için(2 adet köşeli parantez var "age"de) daha güzel görüntü elde ettik. aslında öncekinin aynısı

              age
sex
female  27.915709
male    30.726645

In [381]:
titanic.groupby(["sex","class"], observed=True)[["survived"]].aggregate("mean").unstack()

# titanikteki kadın ve erkeklerin satın aldıkları bilete göre gemi battıktan sonra hayatta kalıp kalamama durumu
# aslında burada pivot görüntüsü elde etmiş olduk

        survived
class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [403]:
# Pivot ile Table

titanic.pivot_table("survived", index="sex", columns="class", aggfunc="mean")

# bize odaklandığın özellik nedir, indexin nedir, başka değerler var mı, hangi işlemi yapacaksın? 
# sorularını sorar ve onları tektek cevapladıktan sonra karşımıza pivot tablomuz gelmiş olur. aggfunc'ı yazmasaydık da mean yapardı çünkü default mean

class      First    Second     Third
sex
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

# Dış Kaynaktan Veri Okumak

.txt, .csv, .xlsx, gibi dosyaları python kodlarıyla açıp üzerlerinde, read, write, delete, update gibi işlemler yapmayı öğrenicez

In [407]:
import pandas as pd

In [431]:
# CSV okuma

pd.read_csv("reading_data/ornekcsv.csv", sep=";")

# jupyter notebook tarafından görüntülenen dizin Numpy Pandas ile veri manipülasyonu klasörü olduğu için 
# dosyaya ulaşmak için reading_data/ornekcsv.csv buraya doğru devam et dedik
# bize gelen veri eğer virgüllerle ayrılmış olsaydı pd.read_csv("reading_data/ornekcsv.csv") kodu yeterli olacaktı ancak
# noktalı virgül ile ayrıldığından dolayı neyde ayırması gerektiğini sep=";" ile yukarıdaki gibi yazdık

# .txt ve .csv formatlarını aynı kodla okuyabiliyoruz 

pd.read_csv("reading_data/ornekcsv.csv", sep=";").head(6)

    a    b    c
0  78   12  1.0
1  78   12  2.0
2  78  324  3.0
3   7    2  4.0
4  88   23  5.0
5   6    2  NaN

In [443]:
# Txt okuma

pd.read_csv("reading_data/duz_metin.txt")

# txt ve csv dosyalarının okuma kodları aynı

    1 2
0   2 2
1   3 2
2   4 2
3   5 2
4   6 2
5  7 2
6   8 2
7   9 2
8  10 2

In [451]:
# Excel okuma
# read_excel komutu ile okunur

pd.read_excel("reading_data/ornekx.xlsx")

      a    b     c
0    78   12   1.0
1    78   12   2.0
2    78  324   3.0
3     7    2   4.0
4    88   23   5.0
5     6    2   NaN
6    56   11   6.0
7     7   12   7.0
8    56   21   7.0
9   346    2   8.0
10    5    1   8.0
11  456   21   8.0
12    3   12  88.0